name: Build and Publish Fedora Dev Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to publish to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./fedora-dev
          file: ./fedora-dev/Dockerfile
          push: true
          tags: ghcr.io/${{ tolower(github.repository_owner) }}/${{ tolower(github.event.repository.name) }}/fedora-dev:latest
