name: Build and Publish Dev Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to publish to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and publish to GHCR
        uses: docker/build-push-action@v6
        with:
          context: ./ubuntu-dev
          file: ./ubuntu-dev/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/playx18/ubuntu-dev:latest